#!/bin/sh

echo "Running post-receive hook"

repo=$HOME/repos/cheatsheets.git
destination=/var/www/cheatsheets

while read oldrev newrev refname
do
    # Get the name of the current branch
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)

    # Checkout master branch
    if [ "$branch" = "master" ]; then
      git --work-tree=$destination --git-dir=$repo checkout -f master
    fi
done

echo "Finished"

